apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: kubernetes/service-app/hello-world
    repoURL: git@github.com/mirdsmulya/fast-campus-argocd-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
